package com.purchase.sls;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.purchase.sls.data.local.GreenDaoNoSqlEntity;

import com.purchase.sls.GreenDaoNoSqlEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoNoSqlEntityDaoConfig;

    private final GreenDaoNoSqlEntityDao greenDaoNoSqlEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoNoSqlEntityDaoConfig = daoConfigMap.get(GreenDaoNoSqlEntityDao.class).clone();
        greenDaoNoSqlEntityDaoConfig.initIdentityScope(type);

        greenDaoNoSqlEntityDao = new GreenDaoNoSqlEntityDao(greenDaoNoSqlEntityDaoConfig, this);

        registerDao(GreenDaoNoSqlEntity.class, greenDaoNoSqlEntityDao);
    }
    
    public void clear() {
        greenDaoNoSqlEntityDaoConfig.clearIdentityScope();
    }

    public GreenDaoNoSqlEntityDao getGreenDaoNoSqlEntityDao() {
        return greenDaoNoSqlEntityDao;
    }

}
