package com.purchase.sls;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.purchase.sls.data.local.GreenDaoNoSqlEntity;
import com.purchase.sls.data.entity.UserInfo;

import com.purchase.sls.GreenDaoNoSqlEntityDao;
import com.purchase.sls.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoNoSqlEntityDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final GreenDaoNoSqlEntityDao greenDaoNoSqlEntityDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoNoSqlEntityDaoConfig = daoConfigMap.get(GreenDaoNoSqlEntityDao.class).clone();
        greenDaoNoSqlEntityDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        greenDaoNoSqlEntityDao = new GreenDaoNoSqlEntityDao(greenDaoNoSqlEntityDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(GreenDaoNoSqlEntity.class, greenDaoNoSqlEntityDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        greenDaoNoSqlEntityDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public GreenDaoNoSqlEntityDao getGreenDaoNoSqlEntityDao() {
        return greenDaoNoSqlEntityDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
